### PR TITLE
Added configuration to draw snooper window on startup & search and filter functionality

### PR DESCRIPTION
**Pull request by GitPaulo**
Just a little thing I added for me that I think you might want in the plugin :3

### CODE REVIEW

**Comment by Maia-Everett** [comment]
Looks good. Just one question: what's the point of

```
pluginState.Visible ^= true;
```

Is it so that `/snooper` toggles the UI instead of showing it? In this case, you should correct the comment above too, as well as the documentation for the slash command (`HelpMessage = "Shows the Snooper window."`).

I also think that the intent would be clearer like this:

```
pluginState.Visible = !pluginState.Visible;
```

If you fix this, I'll merge the PR!

**Comment by GitPaulo** [comment]
> Looks good. Just one question: what's the point of
> 
> ```
> pluginState.Visible ^= true;
> ```
> 
> Is it so that `/snooper` toggles the UI instead of showing it? In this case, you should correct the comment above too, as well as the documentation for the slash command (`HelpMessage = "Shows the Snooper window."`).
> 
> I also think that the intent would be clearer like this:
> 
> ```
> pluginState.Visible = !pluginState.Visible;
> ```
> 
> If you fix this, I'll merge the PR!

Yea sorry I have short form brain rot 😄  - will do!

**Comment by GitPaulo** [comment]
@Maia-Everett I've added a small extra feature. I won't be adding anything else in this PR, review when you have time please ❤️

**Comment by Maia-Everett** [comment]
Merged, thanks! I'll credit you in the next release notes!

**Comment by GitPaulo** [comment]
> Merged, thanks! I'll credit you in the next release notes!

I've found a problem with line breaking I'll address very soon so please don't release anything yet! Ty <3

**Pull request merged**
