### PR TITLE
improve targeting logic

### PR DESCRIPTION
**Pull request by GitPaulo**
A final improvement:

- Prevents mouseover targeting from triggering when the mouse is over the snooper window
- Tries to improve targeting logic by adding a new targeting mode `Joint` which prioritises targeted players over hovered players

TY <3

### CODE REVIEW

**Comment by Maia-Everett** [comment]
Hello!

The PR looks good. Just one cosmetic request: the standard convention in .NET is to use singular enum names, not plural. Please change `Hovermodes` to `HoverMode` (in CamelCase) and then I'll merge it!

**Comment by Maia-Everett** [comment]
Thanks for changing the enum to `CamelCase`. I've also asked to change it from plural to singular.

Please rename `public enum HoverModes` to `public enum HoverMode`.

**Comment by GitPaulo** [comment]
Sorry my bad!

To avoid conflicts, I changed it to `HoverModeType`

**Comment by Maia-Everett** [comment]
Merged, thanks!

**Pull request merged**
